# Generated by Django 4.2.6 on 2023-10-16 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0002_user_register_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_register',
            name='ucpass',
        ),
        migrations.AlterField(
            model_name='user_register',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user_register',
            name='mobile',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='user_register',
            name='uname',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
