# Generated by Django 4.2.6 on 2023-10-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0004_menu_delete_user_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='menu ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
        ),
        migrations.DeleteModel(
            name='menu',
        ),
    ]
