# Generated by Django 4.2.6 on 2023-10-23 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0005_menu1_delete_menu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='menu1',
        ),
    ]
