# Generated by Django 4.2.6 on 2023-10-23 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0007_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='menu1',
            new_name='menus1',
        ),
    ]
