# Generated by Django 4.2.6 on 2023-10-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0008_rename_menu1_menus1'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Restaurant ')),
                ('variety', models.CharField(max_length=50, verbose_name='variety')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
        ),
        migrations.CreateModel(
            name='TopRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Restaurant ')),
                ('variety', models.CharField(max_length=50, verbose_name='variety')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
        ),
    ]
