# Generated by Django 4.2.6 on 2023-10-24 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0009_otherrestaurant_toprestaurant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OtherRestaurant',
        ),
    ]
