# Generated by Django 4.2.6 on 2023-10-25 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0011_dominopizza'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dominopizza',
            old_name='name',
            new_name='foodname',
        ),
    ]
