# Generated by Django 4.2.6 on 2023-10-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0012_rename_name_dominopizza_foodname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=50, verbose_name='Food ')),
                ('foodname', models.CharField(max_length=50, verbose_name='FoodName ')),
                ('rupess', models.BigIntegerField(verbose_name='Cost')),
                ('description', models.CharField(max_length=150, verbose_name='Description ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
        ),
    ]
