# Generated by Django 4.2.6 on 2023-10-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0018_subway_pimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dominopizza',
            name='food',
            field=models.CharField(choices=[(1, 'Veg'), (2, 'Non Veg')], max_length=50, verbose_name='Food '),
        ),
    ]
