# Generated by Django 4.2.6 on 2023-10-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0019_alter_dominopizza_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dominopizza',
            name='food',
            field=models.IntegerField(choices=[(1, 'Veg'), (2, 'Non Veg')], verbose_name='Food '),
        ),
    ]
