# Generated by Django 4.2.6 on 2023-10-29 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0020_alter_dominopizza_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='menufilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('menuid', models.ForeignKey(db_column='menuid', on_delete=django.db.models.deletion.CASCADE, to='food_app.menus1')),
                ('resid', models.ForeignKey(db_column='resid', on_delete=django.db.models.deletion.CASCADE, to='food_app.toprestaurant')),
            ],
        ),
    ]
