# Generated by Django 4.2.6 on 2023-10-30 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0026_rename_cart_cart_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_page',
            name='resid',
        ),
    ]
