# Generated by Django 4.2.6 on 2023-10-30 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0028_cart_page_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_page',
            name='Dominoid',
            field=models.ForeignKey(db_column='Dominoid', null=True, on_delete=django.db.models.deletion.CASCADE, to='food_app.dominopizza'),
        ),
        migrations.AlterField(
            model_name='cart_page',
            name='Subwayid',
            field=models.ForeignKey(db_column='Subwayid', null=True, on_delete=django.db.models.deletion.CASCADE, to='food_app.subway'),
        ),
    ]
