# Generated by Django 4.2.6 on 2023-10-31 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0033_user_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_details',
            old_name='uid',
            new_name='userid',
        ),
    ]
