# Generated by Django 4.2.6 on 2023-11-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0038_alter_customer_details_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toprestaurant',
            name='variety',
            field=models.CharField(max_length=32, verbose_name='variety'),
        ),
    ]
