# Generated by Django 4.2.6 on 2023-11-02 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0042_alter_toprestaurant_variety'),
    ]

    operations = [
        migrations.AddField(
            model_name='dominopizza',
            name='resid',
            field=models.ForeignKey(db_column='resid', default=1, on_delete=django.db.models.deletion.CASCADE, to='food_app.toprestaurant'),
        ),
        migrations.AddField(
            model_name='subway',
            name='resid',
            field=models.ForeignKey(db_column='resid', default=2, on_delete=django.db.models.deletion.CASCADE, to='food_app.toprestaurant'),
        ),
        migrations.CreateModel(
            name='McDonalds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.IntegerField(choices=[(1, 'Veg'), (2, 'Non Veg')], max_length=50, verbose_name='Food ')),
                ('foodname', models.CharField(max_length=50, verbose_name='FoodName ')),
                ('rupess', models.BigIntegerField(verbose_name='Cost')),
                ('description', models.CharField(max_length=500, verbose_name='Description ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('pimage', models.ImageField(upload_to='image')),
                ('resid', models.ForeignKey(db_column='resid', default=3, on_delete=django.db.models.deletion.CASCADE, to='food_app.toprestaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Belgian_Waffle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.IntegerField(choices=[(1, 'Veg'), (2, 'Non Veg')], max_length=50, verbose_name='Food ')),
                ('foodname', models.CharField(max_length=50, verbose_name='FoodName ')),
                ('rupess', models.BigIntegerField(verbose_name='Cost')),
                ('description', models.CharField(max_length=500, verbose_name='Description ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('pimage', models.ImageField(upload_to='image')),
                ('resid', models.ForeignKey(db_column='resid', default=4, on_delete=django.db.models.deletion.CASCADE, to='food_app.toprestaurant')),
            ],
        ),
    ]
