# Generated by Django 4.2.6 on 2023-11-02 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0043_dominopizza_resid_subway_resid_mcdonalds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_page',
            name='McDonaldsid',
            field=models.ForeignKey(db_column='McDonaldsid', null=True, on_delete=django.db.models.deletion.CASCADE, to='food_app.mcdonalds'),
        ),
        migrations.AlterField(
            model_name='belgian_waffle',
            name='food',
            field=models.IntegerField(choices=[(1, 'Veg'), (2, 'Non Veg')], verbose_name='Food '),
        ),
        migrations.AlterField(
            model_name='mcdonalds',
            name='food',
            field=models.IntegerField(choices=[(1, 'Veg'), (2, 'Non Veg')], verbose_name='Food '),
        ),
        migrations.AlterField(
            model_name='mcdonalds',
            name='resid',
            field=models.ForeignKey(db_column='resid', on_delete=django.db.models.deletion.CASCADE, to='food_app.toprestaurant'),
        ),
        migrations.AlterField(
            model_name='subway',
            name='food',
            field=models.IntegerField(choices=[(1, 'Veg'), (2, 'Non Veg')], verbose_name='Food '),
        ),
    ]
