# Generated by Django 4.2.6 on 2023-11-03 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0044_cart_page_mcdonaldsid_alter_belgian_waffle_food_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dominopizza',
            table="Domino's Pizza",
        ),
    ]
