# Generated by Django 4.2.6 on 2023-11-03 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0045_alter_dominopizza_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subway',
            table='Subway',
        ),
    ]
