# Generated by Django 4.2.6 on 2023-11-03 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0046_alter_subway_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subway',
            table='subway',
        ),
    ]
