# Generated by Django 4.2.6 on 2023-11-03 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0047_alter_subway_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dominopizza',
            table=None,
        ),
        migrations.AlterModelTable(
            name='subway',
            table=None,
        ),
    ]
