# Generated by Django 4.2.6 on 2023-11-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0048_alter_dominopizza_table_alter_subway_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='toprestaurant',
            name='NickName',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='toprestaurant',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Restaurant'),
        ),
    ]
