# Generated by Django 4.2.6 on 2023-11-07 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0049_toprestaurant_nickname_alter_toprestaurant_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.IntegerField(choices=[(1, 'Veg'), (2, 'Non Veg')], verbose_name='Food ')),
                ('foodname', models.CharField(max_length=50, verbose_name='FoodName ')),
                ('rupess', models.BigIntegerField(verbose_name='Cost')),
                ('description', models.CharField(max_length=500, verbose_name='Description ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('pimage', models.ImageField(upload_to='image')),
                ('menuid', models.ForeignKey(db_column='menuid', on_delete=django.db.models.deletion.CASCADE, to='food_app.menus1')),
            ],
        ),
    ]
