# Generated by Django 4.2.6 on 2023-11-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0051_alter_subway_foodname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='foodname',
            field=models.CharField(max_length=150, verbose_name='FoodName '),
        ),
    ]
