# Generated by Django 4.2.6 on 2023-11-07 07:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food_app', '0053_cart_delete_cart_page'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cart',
            new_name='cart_page',
        ),
    ]
