# Generated by Django 4.2.6 on 2023-11-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0056_orderconfirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderp',
            name='order_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
