# Generated by Django 4.2.6 on 2023-11-08 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0057_alter_orderp_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderconfirmed',
            name='cid',
        ),
    ]
