# Generated by Django 4.2.6 on 2023-11-08 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0060_alter_orderconfirmed_oid_alter_orderconfirmed_pid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderconfirmed',
            name='oid',
            field=models.ForeignKey(db_column='oid', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='food_app.orderp', to_field='order_id'),
            preserve_default=False,
        ),
    ]
