# Generated by Django 4.2.6 on 2023-11-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0061_alter_orderconfirmed_oid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderconfirmed',
            name='oid',
        ),
        migrations.AddField(
            model_name='orderconfirmed',
            name='order_id',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
