# Generated by Django 4.2.6 on 2023-11-08 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0062_remove_orderconfirmed_oid_orderconfirmed_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderp',
            name='order_id',
        ),
        migrations.AddField(
            model_name='orderp',
            name='rupess',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
