# Generated by Django 4.2.6 on 2023-11-08 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0063_remove_orderp_order_id_orderp_rupess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderp',
            name='rupess',
            field=models.FloatField(null=True),
        ),
    ]
