# Generated by Django 4.2.6 on 2023-11-08 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0064_alter_orderp_rupess'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderconfirmed',
            name='rupess',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderp',
            name='rupess',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
