# Generated by Django 4.2.6 on 2023-11-10 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0065_orderconfirmed_rupess_alter_orderp_rupess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dominopizza',
            name='resid',
        ),
        migrations.RemoveField(
            model_name='mcdonalds',
            name='resid',
        ),
        migrations.RemoveField(
            model_name='menufilter',
            name='menuid',
        ),
        migrations.RemoveField(
            model_name='menufilter',
            name='resid',
        ),
        migrations.RemoveField(
            model_name='subway',
            name='resid',
        ),
        migrations.DeleteModel(
            name='Belgian_Waffle',
        ),
        migrations.DeleteModel(
            name='DominoPizza',
        ),
        migrations.DeleteModel(
            name='McDonalds',
        ),
        migrations.DeleteModel(
            name='menufilter',
        ),
        migrations.DeleteModel(
            name='Subway',
        ),
    ]
